nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: [ '*' ]
            allow_headers: [ 'X-API-Key', 'Accept', 'Content-Type', 'Authorization', 'Prefer' ]
            allow_methods: [ 'GET', 'OPTIONS' ]
            max_age: 3600
